version: '3'
services:

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    volumes:
      - mongo_data:/data/db
      
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=my_db
    networks:
      - my_network

  webservice:
    image: api
    container_name: web
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_DATABASE: my_db
      MONGODB_USERNAME: admin_user
      MONGODB_PASSWORD: admin123
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb
    networks:
      - my_network





volumes:
  mongo_data:

networks:
  my_network:

